// Real outbound links Mohannad maintains, keyed by the item/title/name used in lib/data.ts.
// Sourced from mohannadotaibi.com. Edit here to keep links in sync.

export const links: Record<string, string> = {
  // Software
  ComfyUI: 'https://github.com/comfyanonymous/ComfyUI',
  'LM Studio': 'https://lmstudio.ai/',
  'Ostris AI Toolkit': 'https://ostris.com/',
  'CPU-Z': 'https://www.cpuid.com/softwares/cpu-z.html',
  Kubernetes: 'https://kubernetes.io/',
  'Argo CD': 'https://argo-cd.readthedocs.io/',
  Vault: 'https://www.vaultproject.io/',
  Helm: 'https://helm.sh/',
  Rancher: 'https://rancher.com/',
  Windmill: 'https://www.windmill.dev/',
  Longhorn: 'https://longhorn.io/',
  'Kong Gateway': 'https://konghq.com/kong/',
  DeepSeek: 'https://deepseek.com/',
  Claude: 'https://claude.ai/',
  ChatGPT: 'https://chat.openai.com/',
  'Cursor AI': 'https://www.cursor.com/',
  Linear: 'https://linear.app/',
  Hoppscotch: 'https://hoppscotch.io/',
  DevToys: 'https://devtoys.app/',
  'Ente Auth': 'https://ente.io/auth/',
  Docker: 'https://www.docker.com/',
  Terraform: 'https://www.terraform.io/',
  Ansible: 'https://www.ansible.com/',
  'Docker Desktop': 'https://www.docker.com/products/docker-desktop/',
  'VS Code': 'https://code.visualstudio.com/',
  Insomnia: 'https://insomnia.rest/',
  Termius: 'https://termius.com/',
  'GitHub Desktop': 'https://desktop.github.com/',
  BitWarden: 'https://bitwarden.com/',
  PowerToys: 'https://github.com/microsoft/PowerToys/',
  Warp: 'https://1.1.1.1/',
  'Brave Browser': 'https://brave.com/',
  Figma: 'https://www.figma.com/',
  Slack: 'https://slack.com/',
  Discord: 'https://discord.com/',
  'Streamlabs OBS': 'https://streamlabs.com/',
  'SteelSeries GG': 'https://steelseries.com/gg/',
  Steam: 'https://store.steampowered.com/',
  Stremio: 'https://www.stremio.com/',
  'SAP S4HANA': 'https://help.sap.com/docs/SAP_S4HANA_ON-PREMISE',
  'SAP Ariba': 'https://www.sap.com/mena/products/spend-management/ariba-login.html',
  WinUtil: 'https://github.com/ChrisTitusTech/winutil',
  WinSCP: 'https://winscp.net/eng/download.php',
  'MySQL Workbench': 'https://www.mysql.com/products/workbench/',
  HeidiSQL: 'https://www.heidisql.com/',
  'VMware Workstation': 'https://www.vmware.com/products/workstation-pro.html',
  'VMware ESXi': 'https://www.vmware.com/products/esxi-and-esx.html',
  VirtualBox: 'https://www.virtualbox.org/',
  Fiddler: 'https://www.telerik.com/fiddler/',
  'K-Lite': 'https://codecguide.com/download_kl.htm',
  WinDirStat: 'https://windirstat.net/',
  'Advanced IP Scanner': 'https://www.advanced-ip-scanner.com/',
  Recuva: 'https://www.ccleaner.com/recuva',
  'Revo Uninstaller': 'https://www.revouninstaller.com/',
  'Free Download Manager': 'https://www.freedownloadmanager.org/',
  '7-zip': 'https://www.7-zip.org/',
  CCleaner: 'https://www.ccleaner.com/',
  Grammarly: 'https://developer.grammarly.com/',
  TestDisk: 'https://www.cgsecurity.org/wiki/TestDisk',
  'Screaming Frog': 'https://www.screamingfrog.co.uk/seo-spider/',
  Speccy: 'https://www.ccleaner.com/speccy',
  'GPU-Z': 'https://www.techpowerup.com/download/techpowerup-gpu-z/',
  Chocolatey: 'https://chocolatey.org/',
  Homebrew: 'https://brew.sh/',
  Winget: 'https://learn.microsoft.com/en-us/windows/package-manager/winget/',
  pnpm: 'https://pnpm.io/',
  Bun: 'https://bun.sh/',
  Grafana: 'https://grafana.com/',
  Prometheus: 'https://prometheus.io/',
  Kibana: 'https://www.elastic.co/kibana/',
  Logstash: 'https://www.elastic.co/logstash/',
  'Fluent Bit': 'https://fluentbit.io/',
  Veeam: 'https://www.veeam.com/',
  Coolify: 'https://coolify.io/',

  // Operating Systems
  macOS: 'https://www.apple.com/macos/',
  Windows: 'https://www.microsoft.com/en-us/windows',
  'Kali Linux': 'https://www.kali.org/',
  ParrotOS: 'https://www.parrotsec.org/',
  Ubuntu: 'https://ubuntu.com/',
  CentOS: 'https://www.centos.org/',
  Whonix: 'https://www.whonix.org/',
  'Qubes OS': 'https://www.qubes-os.org/',

  // Languages
  Java: 'https://www.java.com/en/download/',
  Python: 'https://www.python.org/',
  'C#': 'https://docs.microsoft.com/en-us/dotnet/csharp/',
  PHP: 'https://www.php.net/',
  JavaScript: 'https://www.w3schools.com/js/DEFAULT.asp',
  TypeScript: 'https://www.typescriptlang.org/',
  Dart: 'https://dart.dev/',
  Perl: 'https://www.perl.org/',
  VBA: 'https://docs.microsoft.com/en-us/office/vba/library-reference/concepts/getting-started-with-vba-in-office',
  'VB.net': 'https://docs.microsoft.com/en-us/dotnet/visual-basic/',
  HTML: 'https://www.w3schools.com/html/',
  'SASS/SCSS': 'https://sass-lang.com/',
  SQL: 'https://www.w3schools.com/sql/',
  Bash: 'https://www.gnu.org/software/bash/',
  Batch: 'https://www.tutorialspoint.com/batch_script/index.htm',
  PowerShell: 'https://www.tutorialspoint.com/powershell/powershell_scripting.htm',
  Markdown: 'https://www.markdownguide.org/',

  // Frameworks & Tools
  React: 'https://react.dev/',
  'Vue.js': 'https://vuejs.org/',
  'Next.js': 'https://nextjs.org/',
  NuxtJS: 'https://nuxtjs.org/',
  Astro: 'https://astro.build/',
  Flutter: 'https://flutter.dev/',
  Laravel: 'https://laravel.com/',
  CodeIgniter: 'https://codeigniter.com/',
  'ASP.NET': 'https://dotnet.microsoft.com/en-us/apps/aspnet/',
  'Express.js': 'https://expressjs.com/',
  AdonisJS: 'https://adonisjs.com/',
  'Node.js': 'https://nodejs.org/en/',
  ElectronJS: 'https://www.electronjs.org/',
  Strapi: 'https://strapi.io/',
  'WordPress Plugins': 'https://developer.wordpress.org/plugins/',
  jQuery: 'https://jquery.com/',
  Jekyll: 'https://jekyllrb.com/',
  Bootstrap: 'https://getbootstrap.com/',
  Tailwind: 'https://tailwindcss.com/resources/',
  'shadcn/ui': 'https://ui.shadcn.com/',
  Firebase: 'https://firebase.google.com/',
  Expo: 'https://expo.dev/',
  'React Native': 'https://reactnative.dev/',
  Zustand: 'https://zustand-demo.pmnd.rs/',
  Appwrite: 'https://appwrite.io/',

  // Standards
  Microservices: 'https://microservices.io/',
  DevOps: 'https://www.atlassian.com/devops',
  FinOps: 'https://www.finops.org/',
  Serverless: 'https://serverless.css-tricks.com/services/',
  DRY: "https://en.wikipedia.org/wiki/Don't_repeat_yourself",
  '10 Laws to Design By': 'https://3.7designs.co/blog/2010/07/ten-laws-to-design-by/',
  'PSR-2': 'https://www.php-fig.org/psr/psr-2/',
  'PHP The Right Way': 'https://phptherightway.com/',
  'PHP Best Practices': 'https://phpbestpractices.org/',
  'Getting Things Done': 'https://en.wikipedia.org/wiki/Getting_Things_Done',
  'Usability Testing Demystified': 'https://alistapart.com/article/usability-testing-demystified/',
  'Article Publishing Guidelines':
    'https://web.archive.org/web/20120507051131/https://www.readability.com/publishers/guidelines/',

  // Organizations
  '6 Degrees Tech': 'https://www.6degrees.com.sa/',
  'Promotion Efficiency': 'https://www.promoe.com.sa/',
  'Efficiency Center': 'https://www.efficiencys.com.sa/',
  Burooj: 'https://www.Burooj.pro/',
  'Deets.Pro': 'https://www.deets.pro/',
  'Zahma o La': 'https://www.zahmaola.com/',
  Hetzner: 'https://hetzner.cloud/?ref=LoCUaLQgezDA',
  Cloudflare: 'https://www.cloudflare.com/',
  Thiqah: 'https://www.thiqah.sa/',
  'Nothink.org': 'https://www.nothink.org/',
  'Frappe.io': 'https://frappe.io/',
  'Helge Klein / SetACL': 'https://helgeklein.com/',
  DigitalOcean: 'https://www.digitalocean.com/',
  GitHub: 'https://www.github.com/',
  cPanel: 'https://www.cpanel.net/',
  WHMCS: 'https://www.whmcs.com/',
  Clickatell: 'https://www.clickatell.com/',
  'Toot Studio': 'https://toot.com.sa/en/',

  // Bookmarks
  'daily.dev': 'https://app.daily.dev/',
  'Hugging Face': 'https://huggingface.co/',
  'Ali BuSaleh': 'https://www.alibslh.me/',
  'Smashing Magazine': 'https://www.smashingmagazine.com/',
  'David Walsh': 'https://davidwalsh.name/',
  'Abraham Williams': 'https://abrah.am/',
  'Hacker News': 'https://news.ycombinator.com/',
  'BlackHat World': 'https://www.blackhatworld.com/',
  'Tiny Subversions': 'https://tinysubversions.com/',
  FileHippo: 'https://filehippo.com/',
  'Cats Who Code': 'https://catswhocode.com/',
  TechCrunch: 'https://techcrunch.com/',
  '@flaviocopes': 'https://flaviocopes.com/',
  'Tuts+': 'https://tutsplus.com/tutorials',
  SpeckyBoy: 'https://speckyboy.com/',
  'Dynamic Drive': 'https://dynamicdrive.com/',
  'Google Hosted Libraries': 'https://developers.google.com/speed/libraries',
  'iBrand Studio': 'https://ibrandstudio.com/',
  DesignModo: 'https://designmodo.com/',
  AskDaveTaylor: 'https://www.askdavetaylor.com/',
  DeviantArt: 'https://www.deviantart.com/',
  'Product Hunt': 'https://www.producthunt.com/',
  GetApp: 'https://www.getapp.com/',
  Momondo: 'https://www.momondo.com/',
  'UX Booth': 'https://www.uxbooth.com/',
  HowToGeek: 'https://www.howtogeek.com/',
  'PWN Wiki': 'https://pwnwiki.io/#!index.md',
  mubix: 'https://mubix.github.io/',
  'Sahab.net': 'https://www.sahab.net/',
  'Traidnt.net': 'http://web.archive.org/web/20160213150705/http://www.traidnt.net/vb',
  'C4Arab.com': 'https://c4arab.virtualave.net/',
  Alkahf: 'https://web.archive.org/web/20020802175234/https://alkhf.com/',

  // Achievements
  'Arabic Reverse Text Converter': 'https://arabic-keyboard.mo9a7i.com/',
  'GitHub Stats Dashboard': 'https://mo9a7i.github.io/github_stats/',
  'Huawei 5G CPE Pro 2 Port Forwarding Guide': 'https://mo9a7i.github.io/huawei-5g-cpe-pro-2-port-forwarding/',
  'Mother of all Lighthouse Reports': 'https://lighthouse.6d.com.sa/',
  'What to agree on with your dev shop': 'https://github.6degrees.com.sa/',
  'Washing a coffee-stained MBP 13 i7 motherboard': 'https://www.adslgate.com/dsl/showthread.php?t=1180584',
  'Why doesn\u2019t my domain work right after registration?':
    'http://web.archive.org/web/20150517010722/http://www.traidnt.net/vb/traidnt1027285-2/',
  'vBulletinner.sh': 'https://www.swalif.net/softs/swalif68/softs248354/',
  'vBulletinner.sh +': 'http://web.archive.org/web/20160213150705/http://www.traidnt.net/vb/traidnt1298111/',
  NetLogger: 'https://mo9a7i.com/2009/Netloggerexe',
  FTPer: 'https://gist.github.com/mo9a7i/1ad6f6485ee7a490da8db615ff527e4f',
  'Path App API Wrapper': 'https://github.com/mo9a7i/CI_Path_API',

  // Contributions
  'Nebula (CoD)': 'https://github.com/carlssonemil/nebula',
  SaudiOSS: 'https://github.com/mo9a7i/SaudiOSS',
  UniGetUI: 'https://github.com/marticliment/UniGetUI/',
  '@flowdegree/swarmapp-api': 'https://www.npmjs.com/package/@flowdegree/swarmapp-api',
  '@6degrees/node-cron-utils': 'https://www.npmjs.com/package/@6degrees/node-cron-utils',
  '@6degrees/f6snypi': 'https://www.npmjs.com/package/@6degrees/f6snypi',
  '@flowdegree/arabic-strings': 'https://www.npmjs.com/package/@flowdegree/arabic-strings',
  '@flowdegree/spit-it': 'https://www.npmjs.com/package/@flowdegree/spit-it',
}

// Store / official links for each game (keyed by the name in lib/data.ts).
export const gameLinks: Record<string, string> = {
  'Call of Duty: Black Ops 7': 'https://www.callofduty.com/blackops7',
  'Doom 95': 'https://www.amazon.com/Ultimate-Doom-Windows-95/dp/B004UYREC4',
  'Second Life': 'https://secondlife.com/',
  'FiveM GTA': 'https://fivem.net/',
  'Call of Duty: World at War': 'https://store.steampowered.com/app/10090/Call_of_Duty_World_at_War/',
  'Call of Duty: Modern Warfare 2': 'https://store.steampowered.com/app/10180/Call_of_Duty_Modern_Warfare_2/',
  'Call of Duty: Black Ops': 'https://store.steampowered.com/app/42700/Call_of_Duty_Black_Ops/',
  'Call of Duty: Modern Warfare 3': 'https://store.steampowered.com/app/115300/Call_of_Duty_Modern_Warfare_3/',
  'Call of Duty: Black Ops II': 'https://store.steampowered.com/app/202970/Call_of_Duty_Black_Ops_II/',
  'Call of Duty: Ghosts': 'https://www.callofduty.com/ghosts',
  'Call of Duty: Advanced Warfare': 'https://www.callofduty.com/advancedwarfare',
  'Call of Duty: Black Ops III': 'https://www.callofduty.com/blackops3',
  'Call of Duty: Infinite Warfare': 'https://www.callofduty.com/infinitewarfare',
  'Call of Duty: WWII': 'https://www.callofduty.com/wwii',
  'Call of Duty: Black Ops 4': 'https://www.callofduty.com/blackops4',
  'Call of Duty: Modern Warfare': 'https://www.callofduty.com/modernwarfare',
  'Call of Duty: Black Ops Cold War': 'https://www.callofduty.com/blackopscoldwar',
  'Call of Duty: Vanguard': 'https://www.callofduty.com/vanguard',
  'Call of Duty: Modern Warfare II': 'https://www.callofduty.com/modernwarfare2',
  'Call of Duty: Modern Warfare III': 'https://www.callofduty.com/modernwarfare3',
  'Call of Duty: Black Ops 6': 'https://www.callofduty.com/blackops6',
}

/**
 * Returns a favicon/logo URL for a given site.
 * Uses the icons Mohannad already curates on mohannadotaibi.com, keyed by hostname.
 */
export function faviconFor(url?: string): string | null {
  if (!url || url === '#') return null
  try {
    const host = new URL(url).hostname
    return `https://mohannadotaibi.com/assets/images/icons/${host}.png`
  } catch {
    return null
  }
}

/** Google's favicon service, used as a fallback when the curated icon 404s. */
export function faviconFallback(url?: string): string | null {
  if (!url || url === '#') return null
  try {
    const host = new URL(url).hostname
    return `https://www.google.com/s2/favicons?domain=${host}&sz=64`
  } catch {
    return null
  }
}
